"""指標名・内訳名を構成する部品トークンの 中文→(日本語, English) 対訳辞書。

指標名(indicator)・内訳名(kj1)は「本体_内訳_限定」を「_」で連結した合成語。
本辞書で部品を訳し、labels.compose() で全体を自動合成する。
NBSカタログ由来の353部品を網羅（不足時は labels 側で中文フォールバック）。
"""
from __future__ import annotations

TOKEN_LABELS: dict[str, tuple[str, str]] = {
    "36个城市": ("36都市", "36 cities"),
    "36个大中城市平均": ("36大中都市平均", "36 major cities avg"),
    "3G移动电话用户": ("3G携帯電話ユーザー", "3G mobile subscribers"),
    "上年同月=100": ("前年同月=100", "prev-year month=100"),
    "上年同期=100": ("前年同期=100", "prev-year period=100"),
    "与港澳台商合作经营企业": ("香港・マカオ・台湾資本との合作経営企業", "HK/Macau/Taiwan cooperative enterprise"),
    "与港澳台商合资经营企业": ("香港・マカオ・台湾資本との合弁企業", "HK/Macau/Taiwan joint-venture enterprise"),
    "专用设备制造业": ("専用設備製造業", "Special-purpose equipment mfg"),
    "东北地区": ("東北地域", "Northeast region"),
    "东部地区": ("東部地域", "Eastern region"),
    "个人合伙": ("個人組合(パートナーシップ)", "Individual partnership"),
    "个体经营": ("個人経営", "Self-employed business"),
    "中厚宽钢带": ("中厚幅鋼帯", "Medium-heavy wide steel strip"),
    "中型拖拉机": ("中型トラクター", "Medium tractors"),
    "中外合作经营企业": ("中外合作経営企業", "Sino-foreign cooperative enterprise"),
    "中外合资经营企业": ("中外合弁企業", "Sino-foreign joint venture"),
    "中成药": ("中成薬", "Chinese patent medicine"),
    "中空玻璃": ("複層ガラス", "Insulating glass"),
    "中西药品类": ("漢方・西洋薬品類", "Chinese & Western medicines"),
    "中部地区": ("中部地域", "Central region"),
    "乙烯": ("エチレン", "Ethylene"),
    "乡村": ("農村", "Rural"),
    "书报杂志类": ("書籍・新聞・雑誌類", "Books, newspapers & magazines"),
    "乳制品": ("乳製品", "Dairy products"),
    "亏损企业亏损总额": ("赤字企業の赤字総額", "Total losses of loss-making enterprises"),
    "互联网宽带接入用户数": ("インターネットブロードバンド加入者数", "Internet broadband subscribers"),
    "交流电动机": ("交流電動機", "AC motors"),
    "交通运输、仓储和邮政业": ("運輸・倉庫・郵政業", "Transport, storage & postal"),
    "产品产量": ("製品生産量", "Product output"),
    "仪器仪表制造业": ("計器・計測機器製造業", "Instruments & meters mfg"),
    "传真机": ("ファクシミリ", "Fax machines"),
    "住宅": ("住宅", "Residential"),
    "住宅电话用户": ("住宅用固定電話ユーザー", "Residential telephone subscribers"),
    "住宿和餐饮业": ("宿泊・飲食業", "Accommodation & catering"),
    "体育、娱乐用品类": ("スポーツ・娯楽用品類", "Sports & recreation goods"),
    "信息传输、软件和信息技术服务业": ("情報通信・ソフトウェア・ITサービス業", "IT, software & information services"),
    "光电子器件": ("光電子デバイス", "Optoelectronic devices"),
    "光缆": ("光ファイバーケーブル", "Optical fiber cable"),
    "公共管理、社会保障和社会组织": ("公共管理・社会保障・社会団体", "Public admin, social security & organizations"),
    "公共设施管理业": ("公共施設管理業", "Public facilities management"),
    "公路运输": ("道路輸送", "Road transport"),
    "其他企业": ("その他企業", "Other enterprises"),
    "其他制造业": ("その他製造業", "Other manufacturing"),
    "其他工业原材料及半成品类": ("その他工業原材料・半製品類", "Other industrial materials & semi-finished goods"),
    "其他有限责任公司": ("その他有限責任会社", "Other limited liability companies"),
    "其他未列明商品类": ("その他分類外商品", "Other unclassified goods"),
    "其他费用": ("その他費用", "Other expenses"),
    "其他资金": ("その他資金", "Other funds"),
    "其他采矿业": ("その他鉱業", "Other mining"),
    "内资企业": ("内資企業", "Domestic-funded enterprises"),
    "农、林、牧、渔专业及辅助性活动": ("農林牧漁の専門・補助的活動", "Agriculture/forestry/livestock/fishery support"),
    "农、林、牧、渔业": ("農林牧漁業", "Agriculture, forestry, livestock & fishery"),
    "农业": ("農業", "Agriculture"),
    "农副产品类": ("農副産品類", "Agricultural & sideline products"),
    "农副食品加工业": ("農副食品加工業", "Agricultural & sideline food processing"),
    "农用氮、磷、钾化学肥料（折纯）": ("農業用窒素・リン・カリ化学肥料(純分換算)", "Agri N/P/K chemical fertilizer (pure)"),
    "冷轧薄板": ("冷延薄板", "Cold-rolled sheet"),
    "函件": ("郵便物(信書)", "Letters/mail"),
    "初级形态塑料": ("一次形態プラスチック", "Primary-form plastics"),
    "利息支出": ("支払利息", "Interest expense"),
    "利润总额": ("利益総額", "Total profit"),
    "利用外资": ("外資利用", "Utilization of foreign capital"),
    "制造业": ("製造業", "Manufacturing"),
    "办公楼": ("オフィスビル", "Office buildings"),
    "动车组": ("動車組(高速鉄道車両)", "Multiple-unit trains"),
    "包装专用设备": ("包装専用設備", "Packaging machinery"),
    "包裹": ("小包(郵便)", "Parcels"),
    "化妆品类": ("化粧品類", "Cosmetics"),
    "化学农药原药（折有效成分100％）": ("化学農薬原体(有効成分100%換算)", "Chemical pesticide (100% active)"),
    "化学原料和化学制品制造业": ("化学原料・化学製品製造業", "Chemical materials & products mfg"),
    "化学纤维": ("化学繊維", "Chemical fibers"),
    "化学纤维制造业": ("化学繊維製造業", "Chemical fiber mfg"),
    "化学药品原药": ("化学医薬品原体", "Chemical drug APIs"),
    "化工原料类": ("化学工業原料類", "Chemical raw materials"),
    "医药制造业": ("医薬品製造業", "Pharmaceutical mfg"),
    "十种有色金属": ("十種非鉄金属", "Ten non-ferrous metals"),
    "卫生": ("衛生", "Sanitation"),
    "卫生和社会工作": ("衛生・社会事業", "Health & social work"),
    "印刷和记录媒介复制业": ("印刷・記録媒体複製業", "Printing & recording media reproduction"),
    "卷烟": ("紙巻たばこ", "Cigarettes"),
    "原油": ("原油", "Crude oil"),
    "原油加工量": ("原油処理量", "Crude oil processed"),
    "原煤": ("原炭", "Raw coal"),
    "原盐": ("原塩", "Crude salt"),
    "原铝（电解铝）": ("原アルミ(電解アルミ)", "Primary aluminum (electrolytic)"),
    "发动机": ("エンジン", "Engines"),
    "发电机组（发电设备）": ("発電機セット(発電設備)", "Generating sets"),
    "发电量": ("発電量", "Electricity generation"),
    "合成橡胶": ("合成ゴム", "Synthetic rubber"),
    "合成洗涤剂": ("合成洗剤", "Synthetic detergent"),
    "合成纤维": ("合成繊維", "Synthetic fiber"),
    "商业营业用房": ("商業用建物", "Commercial premises"),
    "商品房屋施工面积": ("商品建物施工面積", "Floor space under construction"),
    "商品房竣工面积": ("商品建物竣工面積", "Completed floor space"),
    "商品房销售面积": ("商品建物販売面積", "Floor space of buildings sold"),
    "商品零售价格指数": ("商品小売価格指数", "Retail price index"),
    "啤酒": ("ビール", "Beer"),
    "固定电话主叫通话时长(含IP)": ("固定電話発信通話時間(IP含む)", "Fixed-line outgoing call minutes (incl. IP)"),
    "固定电话用户": ("固定電話ユーザー", "Fixed-line subscribers"),
    "固定资产投资": ("固定資産投資", "Fixed asset investment"),
    "固定资产投资完成额": ("固定資産投資完成額", "Fixed asset investment"),
    "固定长途电话通话时长": ("固定長距離電話通話時間", "Fixed long-distance call minutes"),
    "国内贷款": ("国内借入", "Domestic loans"),
    "国家预算资金": ("国家予算資金", "State budget funds"),
    "国有企业": ("国有企業", "State-owned enterprises"),
    "国有及国有控股": ("国有・国有支配", "State-owned & state-holding"),
    "国有独资公司": ("国有独資会社", "Wholly state-owned company"),
    "城镇": ("都市部(城鎮)", "Urban"),
    "基本型乘用车（轿车）": ("基本型乗用車(セダン)", "Basic passenger cars (sedans)"),
    "塑料制品": ("プラスチック製品", "Plastic products"),
    "复印和胶版印制设备": ("複写・オフセット印刷設備", "Copying & offset printing equipment"),
    "外商及港澳台商投资企业": ("外資及び香港・マカオ・台湾資本投資企業", "Foreign & HK/Macau/Taiwan-invested enterprises"),
    "外商投资企业": ("外資投資企業", "Foreign-invested enterprises"),
    "外商投资股份有限公司": ("外資投資株式会社", "Foreign-invested joint-stock company"),
    "外资企业": ("外資企業", "Foreign-funded enterprises"),
    "大型拖拉机": ("大型トラクター", "Large tractors"),
    "大气污染防治设备": ("大気汚染防止設備", "Air-pollution control equipment"),
    "天然气": ("天然ガス", "Natural gas"),
    "太阳能发电量": ("太陽光発電量", "Solar power generation"),
    "太阳能电池（光伏电池）": ("太陽電池(太陽光)", "Solar cells (PV)"),
    "夹层玻璃": ("合わせガラス", "Laminated glass"),
    "存货": ("棚卸資産", "Inventories"),
    "存货其中产成品": ("棚卸資産のうち製品", "Inventories: finished goods"),
    "客运量": ("旅客輸送量", "Passenger volume"),
    "家具制造业": ("家具製造業", "Furniture mfg"),
    "家具类": ("家具類", "Furniture"),
    "家用冷柜（家用冷冻箱）": ("家庭用冷凍庫", "Household freezers"),
    "家用洗衣机": ("家庭用洗濯機", "Household washing machines"),
    "家用电冰箱（家用冷冻冷藏箱）": ("家庭用冷蔵庫", "Household refrigerators"),
    "家用电器和音像器材类": ("家電・音響映像機器類", "Household appliances & AV equipment"),
    "小型拖拉机": ("小型トラクター", "Small tractors"),
    "居民服务、修理和其他服务业": ("住民サービス・修理その他サービス業", "Resident, repair & other services"),
    "居民消费价格指数": ("消費者物価指数", "Consumer price index"),
    "工业": ("工業", "Industry"),
    "工业增加值": ("工業付加価値", "Industrial value added"),
    "工业机器人": ("産業用ロボット", "Industrial robots"),
    "工业生产者购进价格指数": ("工業生産者購入価格指数", "Producer purchasing price index"),
    "工业锅炉": ("工業用ボイラー", "Industrial boilers"),
    "布": ("布(織物)", "Cloth"),
    "平板玻璃": ("板ガラス", "Flat glass"),
    "应交增值税": ("未払増値税", "VAT payable"),
    "应收账款": ("売掛金", "Accounts receivable"),
    "废弃资源综合利用业": ("廃棄資源総合利用業", "Waste-resource utilization"),
    "建筑业": ("建設業", "Construction"),
    "建筑及装潢材料类": ("建築・内装材料類", "Building & decoration materials"),
    "建筑安装工程": ("建築・据付工事", "Construction & installation works"),
    "建筑材料类及非金属类": ("建材・非金属類", "Building materials & non-metals"),
    "开采专业及辅助性活动": ("採掘専門・補助的活動", "Mining support activities"),
    "当期值": ("当期値", "Current-period value"),
    "彩色电视机": ("カラーテレビ", "Color TVs"),
    "微型计算机设备": ("マイクロコンピュータ機器", "Microcomputer equipment"),
    "快递业务": ("宅配便業務", "Express delivery service"),
    "快递业务量": ("宅配便取扱量", "Express delivery volume"),
    "成品糖": ("精製糖", "Refined sugar"),
    "房地产业": ("不動産業", "Real estate"),
    "房地产开发投资完成额": ("不動産開発投資完成額", "Real estate development investment"),
    "房屋新开工面积": ("建物新規着工面積", "Newly started floor space"),
    "房屋销售面积": ("建物販売面積", "Floor space of buildings sold"),
    "房间空气调节器": ("ルームエアコン", "Room air conditioners"),
    "扩建": ("拡張", "Expansion"),
    "批发和零售业": ("卸売・小売業", "Wholesale & retail"),
    "挖掘机": ("掘削機(ショベル)", "Excavators"),
    "改建": ("改築", "Reconstruction"),
    "教育": ("教育", "Education"),
    "文化、体育和娱乐业": ("文化・スポーツ・娯楽業", "Culture, sports & entertainment"),
    "文化办公用品类": ("文化・事務用品類", "Culture & office supplies"),
    "文化艺术业": ("文化芸術業", "Culture & arts"),
    "文教、工美、体育和娱乐用品制造业": ("文教・工芸美術・スポーツ娯楽用品製造業", "Culture/education/arts/sports goods mfg"),
    "新建": ("新設", "New construction"),
    "新闻纸": ("新聞用紙", "Newsprint"),
    "旅客周转量": ("旅客輸送人キロ", "Passenger turnover"),
    "日用品类": ("日用品類", "Daily-use goods"),
    "有色金属冶炼和压延加工业": ("非鉄金属精錬・圧延加工業", "Non-ferrous metal smelting & rolling"),
    "有色金属材料及电线类": ("非鉄金属材料・電線類", "Non-ferrous metals & wire"),
    "有色金属矿采选业": ("非鉄金属鉱採掘・選鉱業", "Non-ferrous metal mining"),
    "有限责任公司": ("有限責任会社", "Limited liability company"),
    "服装、鞋帽、针纺织品类": ("衣料・靴帽・ニット織物類", "Clothing, footwear & textiles"),
    "服装类": ("衣料類", "Clothing"),
    "木材加工和木、竹、藤、棕、草制品业": ("木材加工・木竹藤製品業", "Wood, bamboo & rattan products"),
    "木材及纸浆类": ("木材・パルプ類", "Timber & pulp"),
    "本年资金来源": ("本年資金源泉", "Funds sources (year to date)"),
    "机制纸及纸板（外购原纸加工除外）": ("機械抄き紙・板紙", "Machine-made paper & paperboard"),
    "林业": ("林業", "Forestry"),
    "柴油": ("軽油(ディーゼル)", "Diesel"),
    "核能发电量": ("原子力発電量", "Nuclear power generation"),
    "橡胶和塑料制品业": ("ゴム・プラスチック製品業", "Rubber & plastics products"),
    "橡胶轮胎外胎": ("ゴムタイヤ(外装)", "Rubber tire casings"),
    "民用钢质船舶": ("民間用鋼製船舶", "Civil steel ships"),
    "民航运输": ("民間航空輸送", "Civil aviation transport"),
    "氧化铝": ("アルミナ(酸化アルミ)", "Alumina"),
    "水上运输业": ("水運業", "Water transport"),
    "水上运输和港口": ("水運・港湾", "Water transport & ports"),
    "水利、环境和公共设施管理业": ("水利・環境・公共施設管理業", "Water, environment & public facilities mgmt"),
    "水利管理业": ("水利管理業", "Water conservancy management"),
    "水力发电量": ("水力発電量", "Hydropower generation"),
    "水泥": ("セメント", "Cement"),
    "水泥专用设备": ("セメント専用設備", "Cement machinery"),
    "水的生产和供应业": ("水の生産・供給業", "Water production & supply"),
    "汇兑": ("為替(送金)", "Remittances"),
    "汽油": ("ガソリン", "Gasoline"),
    "汽车": ("自動車", "Automobiles"),
    "汽车制造业": ("自動車製造業", "Automobile mfg"),
    "汽车类": ("自動車類", "Automobiles"),
    "流动资产合计": ("流動資産合計", "Total current assets"),
    "消费者价格涨跌率": ("消費者物価上昇率", "CPI change rate"),
    "液化天然气": ("液化天然ガス(LNG)", "LNG"),
    "液化石油气": ("液化石油ガス(LPG)", "LPG"),
    "渔业": ("漁業", "Fishery"),
    "港澳台商投资企业": ("香港・マカオ・台湾資本投資企業", "HK/Macau/Taiwan-invested enterprises"),
    "港澳台商投资股份有限公司": ("香港・マカオ・台湾資本投資株式会社", "HK/Macau/Taiwan-invested joint-stock company"),
    "港澳台商独资经营企业": ("香港・マカオ・台湾資本独資企業", "Wholly HK/Macau/Taiwan-owned enterprise"),
    "火力发电量": ("火力発電量", "Thermal power generation"),
    "烟草制品业": ("たばこ製品業", "Tobacco products"),
    "烟酒类": ("たばこ・酒類", "Tobacco & alcohol"),
    "烧碱（折100％）": ("苛性ソーダ(100%換算)", "Caustic soda (100%)"),
    "焊接钢管": ("溶接鋼管", "Welded steel pipe"),
    "焦炭": ("コークス", "Coke"),
    "煤层气": ("炭層ガス", "Coalbed methane"),
    "煤气生产量": ("ガス生産量", "Gas output"),
    "煤油": ("灯油(ケロシン)", "Kerosene"),
    "煤炭开采和洗选业": ("石炭採掘・選炭業", "Coal mining & washing"),
    "燃料、动力类": ("燃料・動力類", "Fuel & power"),
    "燃料油": ("重油(燃料油)", "Fuel oil"),
    "燃气生产和供应业": ("ガス生産・供給業", "Gas production & supply"),
    "生态保护和环境治理业": ("生態保護・環境整備業", "Ecological protection & environmental governance"),
    "生铁": ("銑鉄", "Pig iron"),
    "电信、广播电视和卫星传输服务": ("電気通信・放送・衛星伝送サービス", "Telecom, broadcasting & satellite transmission"),
    "电信业务总量": ("電気通信業務総量", "Total telecom business"),
    "电力、热力、燃气及水生产和供应业": ("電力・熱・ガス・水の生産供給業", "Electricity, heat, gas & water supply"),
    "电力、热力生产和供应业": ("電力・熱の生産供給業", "Electricity & heat production & supply"),
    "电动手提式工具": ("電動ハンドツール", "Electric handheld tools"),
    "电子计算机整机": ("電子計算機本体", "Computers (complete units)"),
    "电工仪器仪表": ("電気計器", "Electrical instruments"),
    "电梯、自动扶梯及升降机": ("エレベーター・エスカレーター", "Elevators, escalators & lifts"),
    "电气机械和器材制造业": ("電気機械・器材製造業", "Electrical machinery & equipment mfg"),
    "畜牧业": ("牧畜業", "Animal husbandry"),
    "白酒（折65度，商品量）": ("白酒(65度換算・商品量)", "Baijiu (65°, commodity vol)"),
    "皮革、毛皮、羽毛及其制品和制鞋业": ("皮革・毛皮・羽毛製品・製靴業", "Leather, fur, feather & footwear"),
    "石油、煤炭及其他燃料加工业": ("石油・石炭その他燃料加工業", "Petroleum, coal & other fuel processing"),
    "石油及制品类": ("石油・石油製品類", "Petroleum & products"),
    "石油和天然气开采业": ("石油・天然ガス採掘業", "Oil & gas extraction"),
    "石油沥青": ("石油アスファルト", "Petroleum asphalt"),
    "石油焦（油渣类）": ("石油コークス", "Petroleum coke"),
    "石脑油": ("ナフサ", "Naphtha"),
    "硫酸（折100％）": ("硫酸(100%換算)", "Sulfuric acid (100%)"),
    "磷矿石（折含五氧化二磷30％）": ("リン鉱石(P2O5 30%換算)", "Phosphate ore (30% P2O5)"),
    "社会消费品零售总额": ("社会消費財小売総額", "Total retail sales of consumer goods"),
    "私营企业": ("私営企業", "Private enterprises"),
    "科学研究和技术服务业": ("科学研究・技術サービス業", "Scientific research & technical services"),
    "租赁和商务服务业": ("リース・商務サービス業", "Leasing & business services"),
    "移动电话用户": ("携帯電話ユーザー", "Mobile phone subscribers"),
    "移动电话通话时长": ("携帯電話通話時間", "Mobile call minutes"),
    "移动短信业务量": ("携帯SMS業務量", "Mobile SMS volume"),
    "移动通信基站设备": ("移動通信基地局設備", "Mobile base-station equipment"),
    "移动通信手持机（手机）": ("携帯電話端末", "Mobile handsets"),
    "程控交换机": ("プログラム制御交換機", "Program-controlled switches"),
    "第一产业": ("第一次産業", "Primary industry"),
    "第三产业": ("第三次産業", "Tertiary industry"),
    "第二产业": ("第二次産業", "Secondary industry"),
    "管理费用": ("管理費", "Administrative expenses"),
    "管道运输业": ("パイプライン輸送業", "Pipeline transport"),
    "粗钢": ("粗鋼", "Crude steel"),
    "粮油、食品、饮料、烟酒类": ("穀油・食品・飲料・たばこ酒類", "Grain/oil, food, beverage, tobacco & alcohol"),
    "粮油、食品类": ("穀油・食品類", "Grain, oil & food"),
    "精制食用植物油": ("精製食用植物油", "Refined edible vegetable oil"),
    "精炼铜（电解铜）": ("精製銅(電気銅)", "Refined copper (electrolytic)"),
    "纯碱（碳酸钠）": ("ソーダ灰(炭酸ナトリウム)", "Soda ash"),
    "纱": ("糸(紡績糸)", "Yarn"),
    "纺织业": ("紡織業", "Textiles"),
    "纺织原料类": ("紡織原料類", "Textile raw materials"),
    "纺织服装、服饰业": ("紡織アパレル・服飾業", "Textile apparel & accessories"),
    "线材（盘条）": ("線材(ワイヤーロッド)", "Wire rod"),
    "联营企业": ("連営企業(共同経営)", "Joint-operation enterprises"),
    "股份制企业": ("株式制企業", "Shareholding enterprises"),
    "股份合作企业": ("株式合作企業", "Joint-stock cooperative enterprises"),
    "股份有限公司": ("株式会社", "Joint-stock limited company"),
    "能源生产量": ("エネルギー生産量", "Energy output"),
    "自筹资金": ("自己調達資金", "Self-raised funds"),
    "航空运输业": ("航空輸送業", "Air transport"),
    "葡萄酒": ("ワイン", "Wine"),
    "蚕丝及交织机织物，含蚕丝≥50%": ("絹・交織織物(絹≥50%)", "Silk & blended woven fabric (silk≥50%)"),
    "装卸搬运和其他运输服务业": ("荷役・運搬その他運輸サービス業", "Loading/unloading & other transport services"),
    "西部地区": ("西部地域", "Western region"),
    "计算机、通信和其他电子设备制造业": ("コンピュータ・通信その他電子機器製造業", "Computer, communication & other electronics mfg"),
    "订销报纸累计数": ("新聞予約発行累計", "Newspaper subscription (cumulative)"),
    "订销杂志累计数": ("雑誌予約発行累計", "Magazine subscription (cumulative)"),
    "设备工器具购置": ("設備・工器具購入", "Equipment & tools purchase"),
    "负债合计": ("負債合計", "Total liabilities"),
    "财务费用": ("財務費用", "Financial expenses"),
    "货物出口额": ("貨物輸出額", "Goods exports"),
    "货物周转量": ("貨物輸送トンキロ", "Freight turnover"),
    "货物进出口额": ("貨物輸出入額", "Goods imports & exports"),
    "货物进口额": ("貨物輸入額", "Goods imports"),
    "货物进口额(美元)": ("貨物輸入額(米ドル)", "Goods imports (USD)"),
    "货运量": ("貨物輸送量", "Freight volume"),
    "贸易顺差(亿本币)": ("貿易黒字(億・自国通貨)", "Trade surplus (100M local currency)"),
    "资产总计(zc)": ("資産合計", "Total assets"),
    "载货汽车": ("貨物自動車(トラック)", "Trucks"),
    "运动型多用途乘用车（SUV）": ("SUV", "SUVs"),
    "通用设备制造业": ("汎用設備製造業", "General-purpose equipment mfg"),
    "通讯器材类": ("通信機器類", "Communication equipment"),
    "造纸和纸制品业": ("製紙・紙製品業", "Paper & paper products"),
    "道路运输业": ("道路輸送業", "Road transport"),
    "邮政业务总量": ("郵政業務総量", "Total postal business"),
    "邮政和电信业务总量(2010年不变价)": ("郵政・電気通信業務総量(2010年不変価格)", "Postal & telecom total (2010 constant prices)"),
    "邮政行业业务收入": ("郵政業務収入", "Postal industry revenue"),
    "配套工程": ("付帯工事", "Supporting works"),
    "酒、饮料和精制茶制造业": ("酒・飲料・精製茶製造業", "Liquor, beverage & refined-tea mfg"),
    "采矿业": ("鉱業", "Mining"),
    "金属冶炼设备": ("金属精錬設備", "Metal smelting equipment"),
    "金属切削机床": ("金属切削工作機械", "Metal-cutting machine tools"),
    "金属制品、机械和设备修理业": ("金属製品・機械設備修理業", "Repair of metal products, machinery & equipment"),
    "金属制品业": ("金属製品業", "Metal products"),
    "金属成形机床": ("金属成形工作機械", "Metal-forming machine tools"),
    "金属集装箱": ("金属コンテナ", "Metal containers"),
    "金融业": ("金融業", "Finance"),
    "金银珠宝类": ("貴金属・宝飾品類", "Gold, silver & jewelry"),
    "钢化玻璃": ("強化ガラス", "Tempered glass"),
    "钢材": ("鋼材", "Steel products"),
    "钢筋": ("鉄筋", "Rebar"),
    "铁合金": ("フェロアロイ(鉄合金)", "Ferroalloys"),
    "铁矿石原矿": ("鉄鉱石原鉱", "Iron ore (raw)"),
    "铁路、船舶、航空航天和其他运输设备制造业": ("鉄道・船舶・航空宇宙その他輸送設備製造業", "Railway, ship, aerospace & other transport equipment mfg"),
    "铁路机车": ("鉄道機関車", "Railway locomotives"),
    "铁路运输": ("鉄道輸送", "Railway transport"),
    "铁路运输业": ("鉄道輸送業", "Railway transport"),
    "铅": ("鉛", "Lead"),
    "铜材": ("銅材", "Copper products"),
    "铝合金": ("アルミ合金", "Aluminum alloy"),
    "铝材": ("アルミ材", "Aluminum products"),
    "销售费用": ("販売費", "Selling expenses"),
    "锂离子电池": ("リチウムイオン電池", "Lithium-ion batteries"),
    "锌": ("亜鉛", "Zinc"),
    "限额以上": ("一定規模以上", "Above designated size"),
    "集体企业": ("集団所有制企業", "Collective enterprises"),
    "集成电路": ("集積回路(IC)", "Integrated circuits"),
    "零售业": ("小売業", "Retail"),
    "非金属矿物制品业": ("非金属鉱物製品業", "Non-metallic mineral products"),
    "非金属矿采选业": ("非金属鉱採掘・選鉱業", "Non-metallic mineral mining"),
    "风力发电量": ("風力発電量", "Wind power generation"),
    "食品制造业": ("食品製造業", "Food mfg"),
    "餐饮业": ("飲食業", "Catering"),
    "饮料": ("飲料", "Beverages"),
    "饮料类": ("飲料類", "Beverages"),
    "饲料": ("飼料", "Animal feed"),
    "饲料生产专用设备": ("飼料生産専用設備", "Feed-production machinery"),
    "鲜、冷藏肉": ("生鮮・冷蔵肉", "Fresh & chilled meat"),
    "鲜果": ("生鮮果物", "Fresh fruit"),
    "鲜瓜果": ("生鮮瓜果", "Fresh melons & fruit"),
    "鲜菜": ("生鮮野菜", "Fresh vegetables"),
    "黑色金属冶炼和压延加工业": ("鉄鋼精錬・圧延加工業", "Ferrous metal smelting & rolling"),
    "黑色金属材料类": ("鉄鋼材料類", "Ferrous metals"),
    "黑色金属矿采选业": ("鉄鉱採掘・選鉱業", "Ferrous metal mining"),
}
